#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$ROOT_DIR/build"
DIST_DIR="$ROOT_DIR/dist"

rm -rf "$BUILD_DIR" "$DIST_DIR"
mkdir -p "$BUILD_DIR" "$DIST_DIR"

cp "$ROOT_DIR/templates/css/variables.css" "$BUILD_DIR/variables.css"
cp "$ROOT_DIR/templates/css/base.css" "$BUILD_DIR/base.css"
cp "$ROOT_DIR/templates/css/navbar.css" "$BUILD_DIR/navbar.css"
cp "$ROOT_DIR/templates/css/spawn.css" "$BUILD_DIR/spawn.css"
sed "s|{% include 'css/|{% include '|g" "$ROOT_DIR/templates/page.html" > "$BUILD_DIR/page.html"
sed "s|{% include 'css/|{% include '|g" "$ROOT_DIR/templates/spawn.html" > "$BUILD_DIR/spawn.html"

OUTPUT="$DIST_DIR/templates.yaml"

{
  echo "# ============================================================"
  echo "# AUTO-GENERATED — DO NOT EDIT"
  echo "#"
  echo "# Generated by scripts/build-dist.sh from jupyterhub-templates/"
  echo "# To update: make dist"
  echo "# ============================================================"
  echo ""
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: jupyterhub-custom-templates"
  echo "  namespace: jupyterhub"
  echo "data:"
  for f in "$BUILD_DIR"/*; do
    key="$(basename "$f")"
    echo "  ${key}: |"
    sed 's/^/    /' "$f"
    echo ""
  done
} > "$OUTPUT"

rm -rf "$BUILD_DIR"

echo "dist/templates.yaml generated ($(wc -l < "$OUTPUT") lines)"
